all : Exercice1 Exercice2 Exercice3 Exercice4

Exercice1 :
	gcc exercice1.c -o Exercice1 -lglut -lGLU -lGL

Exercice2 :
	gcc exercice2.c -o Exercice2 -lglut -lGLU -lGL

Exercice3 :
	gcc exercice3.c -o Exercice3 -lglut -lGLU -lGL

Exercice4 :
	gcc exercice4.c -o Exercice4 -lglut -lGLU -lGL

clean :
	rm Exercice1 Exercice2 Exercice3 Exercice4